apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: chat-app
type: Opaque
data:
  jwt: ICBqd3Q6IGV5SjBlWEFpT2lKS1YxUWlMQ0poYkdjaU9pSklVekkxTmlKOS5leUpwYzNNaU9pSlBibXhwYm1VZ1NsZFVJRUoxYVd4a1pYSWlMQ0pwWVhRaU9qRTNNelEzTWpBNU16QXNJbVY0Y0NJNk1UYzJOakkxTmprek1Dd2lZWFZrSWpvaWRISmhhVzUzYVhSb2MyaDFZbWhoYlM1amIyMGlMQ0p6ZFdJaU9pSnFjbTlqYTJWMFFHVjRZVzF3YkdVdVkyOXRJaXdpUjJsMlpXNU9ZVzFsSWpvaVFXWjZZV3dpTENKVGRYSnVZVzFsSWpvaVVtOWphMlYwSWl3aVJXMWhhV3dpT2lKcWNtOWphMlYwUUdWNFlXMXdiR1V1WTI5dElpd2lVbTlzWlNJNld5SkVaWFpQY0hNaUxDSlFjbTlxWldOMElFRmtiV2x1YVhOMGNtRjBiM0lpWFgwLmVoZWxCYlVVMklGSjhNNXh6UUxfVUZhdE14Q01Tb2pBT3FXUWFaUWdyd2sK